In [32]:
import pandas as pd

In [33]:
# Carico il CSV file
df_new = pd.read_csv('D:\Lorenzo Viaro\Corso Boolean\Corso Data Analytics\FinalProject\Data\Raw\Product_performance.csv')


df_new.head()

,product_id,product_name,product_category,product_department,product_brand,product_cost,product_retail_price,order_item_status,total_sales,total_profit,avg_sale_price,return_rate,user_gender,user_age,user_country,user_latitude,user_longitude,order_item_created_at
0,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Shipped,8,57.757441,150.410004,0.000,M,40,China,31.550649,120.355074,2023-07-22 03:48:37 UTC
1,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Shipped,8,57.757441,150.410004,0.000,M,28,United States,38.809390,-77.620039,2022-10-10 23:29:56 UTC
2,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Complete,8,57.757441,150.410004,0.000,M,44,United States,41.930779,-88.010627,2023-07-26 22:29:03 UTC
3,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Returned,8,57.757441,150.410004,0.125,M,19,United Kingdom,51.514061,-0.299402,2023-03-12 14:12:04 UTC
4,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Returned,8,57.757441,150.410004,0.125,M,59,Brasil,-12.767464,-38.402644,2022-08-10 09:34:21 UTC

In [34]:
# Convert 'order_item_created_at' to datetime and keep only the date
df_new['order_item_created_at'] = pd.to_datetime(df_new['order_item_created_at']).dt.date

In [35]:
# Drop rows where 'product_name' is missing
df_new_cleaned = df_new.dropna(subset=['product_name'])

In [36]:
# Remove duplicates
df_new_cleaned = df_new_cleaned.drop_duplicates()

In [37]:
# Check consistency of 'total_profit'
df_new_cleaned['calculated_profit'] = df_new_cleaned['product_retail_price'] - df_new_cleaned['product_cost']
profit_inconsistencies = df_new_cleaned[abs(df_new_cleaned['total_profit'] - df_new_cleaned['calculated_profit']) > 0.01]

In [38]:
# Replace 'total_profit' with 'calculated_profit' for inconsistent rows
df_new_cleaned.loc[profit_inconsistencies.index, 'total_profit'] = df_new_cleaned.loc[profit_inconsistencies.index, 'calculated_profit']

In [39]:
# Drop the 'calculated_profit' column as it's no longer needed
df_new_cleaned = df_new_cleaned.drop(columns='calculated_profit')
df_new_cleaned.head()

,product_id,product_name,product_category,product_department,product_brand,product_cost,product_retail_price,order_item_status,total_sales,total_profit,avg_sale_price,return_rate,user_gender,user_age,user_country,user_latitude,user_longitude,order_item_created_at
0,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Shipped,8,57.757441,150.410004,0.000,M,40,China,31.550649,120.355074,2023-07-22
1,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Shipped,8,57.757441,150.410004,0.000,M,28,United States,38.809390,-77.620039,2022-10-10
2,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Complete,8,57.757441,150.410004,0.000,M,44,United States,41.930779,-88.010627,2023-07-26
3,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Returned,8,57.757441,150.410004,0.125,M,19,United Kingdom,51.514061,-0.299402,2023-03-12
4,27569,2XU Men's Swimmers Compression Long Sleeve Top,Swim,Men,2XU,92.652563,150.410004,Returned,8,57.757441,150.410004,0.125,M,59,Brasil,-12.767464,-38.402644,2022-08-10

In [40]:
# Check consistency again
df_new_cleaned['calculated_profit'] = df_new_cleaned['product_retail_price'] - df_new_cleaned['product_cost']
profit_inconsistencies_after = df_new_cleaned[abs(df_new_cleaned['total_profit'] - df_new_cleaned['calculated_profit']) > 0.01]
df_new_cleaned = df_new_cleaned.drop(columns='calculated_profit')

In [41]:
#Check user_country column unique values
print(df_new_cleaned['user_country'].unique())

['China' 'United States' 'United Kingdom' 'Brasil' 'Spain' 'France'
 'South Korea' 'Germany' 'Belgium' 'Japan' 'Australia' 'Colombia' 'Poland'
 'Austria' 'España']

In [42]:
# Replace "España" with "Spain" and "Brasil" with "Brazil"
df_new_cleaned['user_country'] = df_new_cleaned['user_country'].replace({"España": "Spain", "Brasil": "Brazil"})

In [43]:
# Check the 'product_brand' column for anomalies
unique_brands = df_new_cleaned['product_brand'].value_counts()
unique_brands

Allegra K                5236
Calvin Klein             2733
Carhartt                 2126
Hanes                    1730
Volcom                   1592
                         ...
Billionaire Boys Club       1
ShimmyShimmy                1
Dasha                       1
Macks Prairie Wings         1
turkishtowels               1
Name: product_brand, Length: 2749, dtype: int64

In [ ]:
# Save the cleaned data to a new CSV file
df_new_cleaned.to_csv('Product_performance_cleaned.csv', index=False)